# Generated by Django 5.0.6 on 2024-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('schedule', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                ('float_field', models.FloatField()),
                ('cgpa', models.DecimalField(decimal_places=5, max_digits=5)),
                ('careerpath', models.BooleanField()),
                ('binary_field', models.BinaryField()),
                ('big_integer_field', models.BigIntegerField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('time_field', models.TimeField()),
            ],
        ),
    ]
